name: Tool Release

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tools-release:
    name: Tool Release
    uses: polusai/image-tools/.github/workflows/package-release.yml@master
    with:
      repo_name: "tabular-tools"
    secrets: inherit
