name: Package tests

on:
  pull_request:
    branches:
      - main
      - master
      - dev
  push:
    branches-ignore:
      - main
      - master
      - dev

permissions:
  contents: read

jobs:
  tools-tests:
    name: Tool Tests
    uses: polusai/image-tools/.github/workflows/package-tests.yml@master
